update

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -21,15 +21,8 @@ error() {
 	exit 1
 }
 
-if [ -f $1/$erxes_ui_dir/package.json ]; then
-  echo "erxes ui app detected!" && exit 0
+if [ -f $1/$erxes_ui_dir/package.json ] && [ -f $1/$erxes_widgets_dir/package.json ]; then
+  echo "erxes detected" && exit 0
 else
-  echo "no erxes ui app detected!" | error && exit 1
+  echo "no erxes detected" | error && exit 1
 fi
-
-if [ -f $1/$erxes_widgets_dir/package.json ]; then
-  echo "erxes widgets app detected!" && exit 0
-else
-  echo "no erxes widgets app detected!" | error && exit 1
-fi
-
